baseURL = 'https://hugo.hechangjia.cn/'

title = '小镇错题家-中国式的西西弗斯'
description = '贺昌嘉的hugo网站'
author = '贺昌嘉'

[module]
  [[module.imports]]
    path = "github.com/D-Sketon/hugo-theme-reimu"



[markup.highlight]
guessSyntax = true
noClasses = false

[markup.goldmark.extensions.passthrough]
enable = true
delimiters.block = [["\\[", "\\]"], ["$$", "$$"]]
delimiters.inline = [["\\(", "\\)"], ["$", "$"]]

